config/routes.rb
Rails.application.routes.draw do
 
  resources :scores

 

  devise_for :users
  
  get 'welcome/index'

  resources :libros do

     resources :reviews
     
  end

  root 'welcome#index'

end

app/models/libro.rb
class Libro < ActiveRecord::Base

	has_many :reviews
	has_many :scores
	has_attached_file :image, styles: { medium: "800x800#", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
	def self.search(params)
	  where("titulo LIKE ?  or autor LIKE ? or ISBN LIKE ?", 
	  	      params[:search_titulo] , params[:search_autor] , params[:search_isbn]) 
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :libro
	belongs_to :user
end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :libro
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
    if !params.empty?
      @libros_busqueda = Libro.search(params)
    else
      @libros_busqueda = Libro.all
    end
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:titulo, :autor, :ISBN, :reseña, :calificacion)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_libro

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.new(review_params)
    @review.libro = @libro


    respond_to do |format|
      if @review.save
        format.html { redirect_to @libro, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

     def set_libro
      @libro = Libro.find(params[:libro_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:titulo, :contenido, :creador, :libro)
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:user_id, :libro_id, :score)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Boock Store</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-inverse navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="dropdown">
              <a aria-expanded="true" href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i><%= current_user.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to edit_user_registration_path do %>
                  <i class="fa fa-gear"></i> Settings
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i> Log Out
                  <% end %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Log in</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/libros/_form.html.erb
<%= form_for(@libro, html: { class: "form-horizontal", role: "form", multipart: true }) do |f| %>
  <% if @libro.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h4>

      <ul>
      <% @libro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :titulo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :titulo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :autor, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :autor, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ISBN, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :ISBN, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/libros/edit.html.erb
<div class="page-header">
  <%= link_to libros_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @libro, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing libro</h1>
</div>

<%= render 'form' %>

app/views/libros/index.html.erb
<%= form_tag(libros_path, :method => "get", id: "search-form") do %>
  <div class="row">
    <div class="col-md-3">
      <%= text_field_tag :search_titulo, params[:search_titulo], class: "form-control", placeholder: "Search Titulo" %>
    </div>
    <div class="col-md-3">
       <%= text_field_tag :search_autor, params[:search_autor], class: "form-control", placeholder: "Search Autor" %>
    </div>
    <div class="col-md-3">
      <%= text_field_tag :search_isbn, params[:search_isbn], class: "form-control", placeholder: "Search ISBN" %>
    </div>
    <div class="col-md-3">
       <%= submit_tag "Go!", class: "btn btn-danger"  %>
    </div>
  </div>
<% end %>

<% if @libros_busqueda.present? %>
  <div class="page-header">
    <%= link_to new_libro_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Libro
    <% end %>
    <h1>Listing libros</h1>
  </div>

  <div class="container marketing">
    <div class="row">
      <%= content_tag_for(:tr, @libros_busqueda) do |libro| %>
        <div class="col-lg-4">
          <div class="thumbnail">
            <%= image_tag libro.image.url(:medium) %>
            <div class="caption">
              <h3><%= libro.titulo %></h3>
              <strong>Autor:</strong> <p><%= libro.autor %></p>
              <strong>ISBN:</strong><p><%= libro.ISBN %></p>
              <p><a><%= link_to 'View libro »', libro, class: "btn btn-primary" %></a></p>
            </div>
          </div>
        </div>
      <% end %>
    </div><!-- /.row -->
  </div>
<% else %>
  <div class="page-header">
    <%= link_to new_libro_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Libro
    <% end %>
    <h1>Listing libros</h1>
  </div>
  <div class="container marketing">
    <div class="row">
      <%= content_tag_for(:tr, @libros) do |libro| %>
        <div class="col-lg-4">
          <div class="thumbnail">
            <%= image_tag libro.image.url(:medium) %>
            <div class="caption">
              <h3><%= libro.titulo %></h3>
              <strong>Autor:</strong> <p><%= libro.autor %></p>
              <strong>ISBN:</strong><p><%= libro.ISBN %></p>
              <p><a><%= link_to 'View libro »', libro, class: "btn btn-primary" %></a></p>
            </div>
          </div>
        </div>
      <% end %>
    </div><!-- /.row -->
  </div>
<% end %>

app/views/libros/new.html.erb
<div class="page-header">
  <%= link_to libros_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New libro</h1>
</div>

<%= render 'form' %>

app/views/libros/show.html.erb
<div class="page-header">
  <%= link_to libros_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_libro_path(@libro), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <%= link_to new_libro_review_path(@libro), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Create review
  <% end %>
  <h1>Show libro</h1>
</div>
<div class="jumbotron">
  <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="thumbnail">
          <%= image_tag @libro.image.url(:medium) %>
          <div class="caption">
            <h3><%= @libro.titulo %></h3>
            <strong>Autor:</strong> <p><%= @libro.autor %></p>
            <strong>ISBN:</strong><p><%= @libro.ISBN %></p>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for [@libro, @review], html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @review.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :titulo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :titulo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contenido, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :contenido, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="page-header">
  <%= link_to libros_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Editing review</h1>
</div>

<%= render 'form' %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th>Creador</th>
      <th>Libro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.titulo %></td>
        <td><%= review.contenido %></td>
        <td><%= review.creador %></td>
        <td><%= review.libro %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reviews/new.html.erb
<div class="page-header">
  <%= link_to libro_reviews_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New libro</h1>
</div>

<%= render 'form' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @review.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @review.contenido %>
</p>

<p>
  <strong>Creador:</strong>
  <%= @review.user.email %>
</p>

<p>
  <strong>Libro:</strong>
  <%= @review.libro %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :libro_id %><br>
    <%= f.number_field :libro_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scores</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Libro</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.user_id %></td>
        <td><%= score.libro_id %></td>
        <td><%= score.score %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @score.user_id %>
</p>

<p>
  <strong>Libro:</strong>
  <%= @score.libro_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>

app/views/welcome/index.html.erb
<div class="jumbotron">
 	<h1>Bienvenidos a la tienda online BookStore</h1>
	<%= link_to 'View Books »', libros_path, class: "btn btn-danger btn-lg" %>
</div>